name: Build and Deploy OTA

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Arduino libraries
        run: |
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "PubSubClient"

      - name: Install ESP8266 core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      - name: Compile sketch
        run: |
          arduino-cli compile \
            --fqbn esp8266:esp8266:nodemcuv2 \
            --build-property build.extra_flags='-DFW_VERSION="${{ github.run_number }}"' \
            firmware/firmware.ino --output-dir build

      - name: Prepare OTA files
        run: |
          VERSION="${{ github.run_number }}"
          mkdir -p ota

          if [ -f ota/firmware-latest.bin ]; then
            mv ota/firmware-latest.bin ota/firmware-prev.bin
          fi

          cp build/firmware.ino.bin ota/firmware-latest.bin

          echo "{ \"version\": \"$VERSION\", \"url\": \"https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/firmware-latest.bin\" }" > ota/ota.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ota
